
project_id = "trvivjdizuimjvjxqcuu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[functions]]
name = "tiktok-profile"
verify_jwt = true

[[functions]]
name = "check_license_expiration"
verify_jwt = false

[[functions]]
name = "create_video_analyses_table"
verify_jwt = true

[[functions]]
name = "exec_sql"
verify_jwt = true
